version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    env_file:
      - ./backend/.env.docker
    volumes:
      - ./backend:/app/backend
      - /app/backend/vendor
      - /app/backend/node_modules
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - laravel_network

  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile.scheduler
    container_name: laravel_scheduler
    restart: unless-stopped
    env_file:
      - ./backend/.env.docker
    depends_on:
      - backend
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: take_home
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    container_name: react_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
